### ISSUE TITLE
ListZoneRulesets does not produce expected output

### ISSUE THREAD

**Issue by Demonsthere** [cloudflare/cloudflare-go#1262]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.64

### Go environment

```shell
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/foo/Library/Caches/go-build"
GOENV="/Users/foo/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/foo/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/foo/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go@1.19/1.19.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go@1.19/1.19.6/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cb/tjw9rzkd0y95s9xwkm4gfwlw0000gq/T/go-build976933174=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Expected output

In my CF project I have a set of legacy RateLimit rules, which i can operate with using the [RateLimit](https://github.com/cloudflare/cloudflare-go/blob/master/rate_limiting.go) objects, as well as a new rule created in the UI using the new api, with RuleSets, as seen in the screenshot:

![image (1)](https://user-images.githubusercontent.com/13346689/230292963-54760fc4-473e-4485-985b-d023d5688595.png)

When i try using the new RuleSet API to list my rules (using [this docs](https://developers.cloudflare.com/ruleset-engine/rulesets-api/view/#list-existing-rulesets) as guidelines) I only see some CF managed rules, but not those I have created. 

### Actual output

Output formatted into yaml format:

```yaml
- description: Created by the Cloudflare security team, this ruleset is designed to
    provide protection for free zones
  id: 77454fe2d30c4220b5701f6fdfb893ba
  kind: managed
  last_updated: "2023-03-02T15:21:02.819432Z"
  name: Cloudflare Managed Log4J Ruleset
  phase: http_request_firewall_managed
  rules: null
  version: "50"
- description: Created by the Cloudflare security team, this ruleset is designed to
    provide fast and effective protection for all your applications. It is frequently
    updated to cover new vulnerabilities and reduce false positives.
  id: efb7b8c949ac4650a09736fc376e9aee
  kind: managed
  last_updated: "2023-04-03T15:58:39.450109Z"
  name: Cloudflare Managed Ruleset
  phase: http_request_firewall_managed
  rules: null
  version: "135"
- description: Automatic mitigation of HTTP-based DDoS attacks. Cloudflare routinely
    adds signatures to address new attack vectors. Additional configuration allows
    you to customize the sensitivity of each rule and the performed mitigation action.
  id: 4d21379b4f9f4bb088e0729962c8b3cf
  kind: managed
  last_updated: "2023-04-05T17:53:22.946376Z"
  name: DDoS L7 ruleset
  phase: ddos_l7
  rules: null
  version: "1230"
- description: Created by the Cloudflare security team, this ruleset is designed to
    provide protection for free zones
  id: 77454fe2d30c4220b5701f6fdfb893ba
  kind: managed
  last_updated: "2023-03-02T15:21:02.819432Z"
  name: Cloudflare Managed Log4J Ruleset
  phase: http_request_firewall_managed
  rules: null
  version: "50"
- description: Automatic mitigation of HTTP-based DDoS attacks. Cloudflare routinely
    adds signatures to address new attack vectors. Additional configuration allows
    you to customize the sensitivity of each rule and the performed mitigation action.
  id: 4d21379b4f9f4bb088e0729962c8b3cf
  kind: managed
  last_updated: "2023-04-05T17:53:22.946376Z"
  name: DDoS L7 ruleset
  phase: ddos_l7
  rules: null
  version: "1230"
- id: e4d2d76d10c94f659ef6602b9d02e4d4
  kind: zone
  last_updated: "2021-10-15T13:48:02.212631Z"
  name: default
  phase: http_ratelimit
  rules: null
  version: "3"
```

As you can see the API list some RuleSets, for all phases, including `http_ratelimit` but I do not get the one rule I have created via the UI.

### Code demonstrating the issue

```go
# client is an wrapper around cloudflare.API from this library
var rules []cloudflare.Ruleset
for _, zone := range client.Zones {
  all, err := client.API.ListZoneRulesets(ctx, zone)
  if err != nil {
    return errors.WithStack(err)
  }
  for _, limit := range all {
    rules = append(rules, limit)
  }
}
```

### Steps to reproduce

1. Create an Advanced Rateimit rule via the UI
2. Try to list it using either `ListZoneRulesets(ctx, zone)` or `ListAccountRulesets(ctx, client.API.AccountID)`
3. Don't get the desired output

Am I using the wrong object/methods of the library, or does the library not yet support the Advanced RateLimit objects using RuleSets?
